name: signup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ✅ this line stays here!

# ✅ This configuration should be OUTSIDE dev_dependencies
flutter_launcher_icons:
  image_path: "icons/login.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - icons/

